version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  usuarios:
    build: ./usuarios
    image: salome0rivas/usuarios-service
    ports:
      - "3001:3001"
    links:
      - db

  productos:
    build: ./productos
    image: salome0rivas/productos-service
    ports:
      - "3002:3002"
    links:
      - db

  ordenes:
    build: ./ordenes
    image: salome0rivas/ordenes-service
    ports:
      - "3003:3003"
    links:
      - db
      - usuarios
      - productos

  microweb:
    build: ./microWeb
    image: salome0rivas/microweb
    ports:
      - "8080:80"
    links:
      - usuarios
      - productos
      - ordenes
