services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  usuarios:
    build: ./usuarios
    image: salome0rivas/usuarios-service
    expose:
      - "3001"
    deploy:
        placement:
           constraints:
               - node.hostname == servidorUbuntu1
    links:
      - db

  productos:
    build: ./productos
    image: salome0rivas/productos-service
    ports:
      - "3002:3002"
    deploy:
        placement:
           constraints:
               - node.hostname == servidorUbuntu1
    links:
      - db

  ordenes:
    build: ./ordenes
    image: salome0rivas/ordenes-service
    ports:
      - "3003:3003"
    deploy:
        placement:
           constraints:
               - node.hostname == servidorUbuntu1

    links:
      - db
      - usuarios
      - productos

  microweb:
    build: ./microWeb
    image: salome0rivas/microweb
    ports:
      - "8080:80"
    deploy:
        placement:
           constraints:
               - node.hostname == servidorUbuntu2
    links:
      - usuarios
      - productos
      - ordenes
  haproxy:
    image: haproxy:latest
    ports:
      - "3080:3080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - usuarios
      - productos
      - ordenes
